[variables]
PYTHON_VERSION = "3.10"

[phases.setup]
nixPkgs = ["python310", "git", "ffmpeg"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn companion_project.wsgi:application"